// Tests the review page helpers against the demo report generated by the
// PowerShell module (scripts/Update-DemoData.ps1).
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

import {
  ReportError,
  compareCatalogs,
  filterRows,
  lookupUsers,
  recommendationsFor,
  severityCounts,
  toCsv,
  validateReport,
} from '../../site/lib/review.js';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..');
const report = JSON.parse(readFileSync(path.join(root, 'site/data/demo-report.json'), 'utf8'));

test('the demo report is valid and matches its summary', () => {
  validateReport(report);
  assert.equal(report.catalogs.length, report.summary.catalogs);
  assert.equal(report.machines.length, report.summary.machines);
  assert.deepEqual(severityCounts(report.recommendations), report.summary.recommendations);
});

test('a snapshot or foreign JSON is rejected with a clear message', () => {
  assert.throws(() => validateReport({ schemaVersion: 1, catalogs: [] }), ReportError);
  assert.throws(() => validateReport([]), /not a JSON object/);
  assert.throws(() => validateReport({ ...report, schemaVersion: 2 }), /schema version 2/);
  assert.throws(() => validateReport({ ...report, machines: undefined }), /"machines"/);
});

test('filtering matches every word in any column, ignoring case', () => {
  const rows = [{ a: 'CORP\\ana.alves', b: ['GRP-Dept-Finance'] }, { a: 'CORP\\bruno', b: ['GRP-Dept-Sales'] }];
  assert.deepEqual(filterRows(rows, 'ana finance', ['a', 'b']), [rows[0]]);
  assert.deepEqual(filterRows(rows, '  ', ['a']), rows);
  assert.deepEqual(filterRows(rows, 'nobody', ['a', 'b']), []);
});

test('CSV quotes separators and neutralizes formulas', () => {
  const csv = toCsv([{ label: 'Name', key: 'name' }, { label: 'Note', key: 'note' }], [
    { name: '=HYPERLINK("http://x")', note: 'a,b' },
    { name: '+1', note: 'line\nbreak' },
    { name: '@cmd', note: '-2' },
    { name: 'plain', note: null },
  ]);
  assert.equal(csv, [
    'Name,Note',
    '"\'=HYPERLINK(""http://x"")","a,b"',
    '\'+1,"line\nbreak"',
    '\'@cmd,\'-2',
    'plain,',
    '',
  ].join('\r\n'));
});

test('recommendations can be narrowed to one catalog', () => {
  const engineering = recommendationsFor(report, 'MC-LIS-W11-DED-ENGINEERING').map((item) => item.id);
  assert.ok(engineering.includes('CCB005'));
  assert.ok(!engineering.includes('CCB006'));
  assert.equal(recommendationsFor(report).length, report.recommendations.length);
});

test('comparing catalogs lists shared users and software differences', () => {
  const result = compareCatalogs(report, ['MC-LIS-W11-POOL-FINANCE', 'MC-LIS-W11-POOL-GENERAL']);
  assert.deepEqual(result.catalogs, ['MC-LIS-W11-POOL-FINANCE', 'MC-LIS-W11-POOL-GENERAL']);
  assert.equal(result.sharedByAll, 11);
  const chrome = result.software.find((row) => row.name === 'Google Chrome');
  assert.equal(chrome.differs, true);
  assert.deepEqual(chrome.catalogs, { 'MC-LIS-W11-POOL-FINANCE': ['126.0.6478.183'], 'MC-LIS-W11-POOL-GENERAL': ['128.0.6613.138'] });
  const sap = result.software.find((row) => row.name === 'SAP GUI for Windows');
  assert.equal(sap.missing, true);
  assert.equal(sap.differs, false);
  assert.equal(result.software[0].differs, true, 'version differences sort first');
});

test('blocked entries never count as shared access', () => {
  const result = compareCatalogs(report, ['MC-LIS-W11-DED-ENGINEERING', 'MC-LIS-S22-MS-SHARED']);
  const contractor = result.users.find((row) => row.user === 'CORP\\karin.duarte');
  assert.deepEqual(Object.keys(contractor.catalogs), ['MC-LIS-S22-MS-SHARED']);
});

test('user lookup returns every path for matching users', () => {
  const [user] = lookupUsers(report, 'diego esteves');
  assert.equal(user.name, 'CORP\\diego.esteves');
  assert.equal(user.enabled, false);
  assert.deepEqual(user.entries.map((entry) => entry.catalog).sort(), ['MC-LIS-S22-MS-SHARED', 'MC-LIS-W11-DED-ENGINEERING']);
  assert.equal(user.entries.find((entry) => entry.catalog === 'MC-LIS-W11-DED-ENGINEERING').machine, 'CORP\\LISW11ENG006');
  assert.deepEqual(lookupUsers(report, ''), []);
});
